from os import getenv

DEBUG = bool(getenv('DEBUG', 0))
SQLALCHEMY_DATABASE_URI = getenv('SQLALCHEMY_URI')
MONGODB_HOST = getenv('MONGODB_URI')
SECRET_KEY = getenv('SECRET_KEY')
THREADS_PER_PAGE = 2
SQLALCHEMY_TRACK_MODIFICATIONS = False
